### PR TITLE
Add nav arrows for supporters on home page

### LINKED ISSUE #2: Add Clickable Arrow to Our Supporters Slider on Home Page
# Summary
Please add arrows on the Our Supporters slider on the Home page. Users can currently click and drag to advance the slider, but this is not intuitive and it would be very helpful to have an easier way to navigate the slider. 

This is the slider:
image

Please let me know if you have any questions! 

# Criteria for Completion
 
 - [ ] Visitors to the website can click on the arrows to advance the slider.

### PR DESCRIPTION
**Pull request by FionaDL**
Hello, this PR closes #2 

I have adjusted the owl carousel javascript and css to include previous and next arrows on either side of the supporters on the home page. I turned off the autoplay because it seemed to be acting a little buggy, but let me know if you want me to turn it back on. 

I used the blue color from the curly brackets as shown here:
Screen Shot 2021-02-17 at 12 51 38 PM
However, I could change it to black in you prefer:
Screen Shot 2021-02-17 at 1 35 27 PM

### CODE REVIEW

**Comment by meg-gutshall** [comment]
Hey @FionaDL! Thank you for your PR, I just saw it today! I'll take a look at it and get back to you with any thoughts but the screen shot looks great!

**Review by meg-gutshall — CHANGES_REQUESTED** [review]
Hi @FionaDL! Thank you for your patience in waiting for my in response—I had to check in with the PM on the autoplay and heard back yesterday. In new a few quick fixes and then I'd love to merge this in!

# Changes

## Nav Arrows

- [x] Here is the hex code from the blue curly braces: #03777E. Could you please adjust the arrows to match?
- [ ] Is it possible to thin out the arrows? I know they're Font Awesome icons so I'm not sure how much you can manipulate them but it would be nice if they had the same (or similar) thickness as the curly braces above. If it can't be done, that's fine, just let me know!
- [ ] Can you add a bit more margin between the arrows and the logo slider? Visually they look a bit scrunched up. I'm thinking 4rem or 5rem? Play with it and see what looks good.

## Slider Motion

- [ ] Can you please keep the autoplay feature on?

### Slider Functioning

What do you mean when you say the slider was acting buggy?

I know that Owl Carousel isn't the best slider we could be using; it was built into the theme so that's why we went with it. It's very strange actually because the theme uses Owl Carousel for some elements (i.e. the Supporters slider you're working on) and Slick for the splash slider at the very top of the page.

I'm not married to this tool and in fact have looked into others, I just haven't implemented anything new because we were focused on getting the MVP done and out. You can see my notes in `.github/docs/assets.md` and if you have any suggestions or would like to implement a new slider tool, I'm all ears!

Thank you so very much for your contribution!

**Comment by FionaDL** [comment]
@meg-gutshall I think I have addressed all of your comments :)

1. I changed the hexcode to match the curly braces
2. I tried to match the thickness of the arrows to the curly braces as best I could
3. Added 4em of margin
4. Turned autoplay on (it's a little weird if you push the arrow around the same time the autoplay would automatically move because it looks like something happened that wasn't quite right). I don't think it's a big deal though. 

I saw that you are interested in moving to a different slider, I will send this fix for now, but keep that in mind as a possible future project. Let me know if you prefer any more changes!

Screen Shot 2021-03-04 at 4 56 29 PM

**Pull request merged**
