### PR TITLE
Responsive projects grid

### PR DESCRIPTION
**Pull request by arielj**
This PR makes the projects' grid responsive. Closes this issue https://github.com/rubyforgood/rubyforgood.org/issues/22

Iphone5 (320px wide):
localhost_4000_our-work_impact(iPhone 5_SE) (1)

IphoneX (375px wide):
localhost_4000_our-work_impact(iPhone X)

Pixel 2 (410px wide):
localhost_4000_our-work_impact(Pixel 2)

Tablet width:
localhost_4000_our-work_impact

Desktop (it stays at this size for larger screens)
localhost_4000_our-work_impact (1)

### CODE REVIEW

**Comment by meg-gutshall** [comment]
# PR Feedback

Hi @arielj! Thank you again for being patient while waiting for my response on this PR.

## Layout Formatting

I noticed that you used CSS grid to make the project boxes responsive. Is there a reason you chose grid over Bootstrap? That's the CSS framework we're currently implementing (I need to update it to v5.0 still).

Actually I'm just realizing now that some documentation wasn't brought over from the original repo we started this site on so you wouldn't have known that unless you're already familiar with Bootstrap's syntax. Ugh!

If you want to take a look at [Bootstrap Grid System's `.row-cols-*` class](https://getbootstrap.com/docs/4.6/layout/grid/#row-columns), you'll see how it works a lot like CSS grid. I'd prefer we use this to keep the same system throughout the codebase, plus it doesn't give off that shaky resizing effect as the user adjusts the window.

## Breakpoints

The number of columns you used at each breakpoint looks good to me! There was just one section that was a bit off. At `546px` it's a 2-column grid and at `547px` it jumps to a 3-column grid. Then at `578px` it reduces back down to a 2-column grid. Since it's such a short range, I'm assuming it's just a fluke. Could you look into that please?

## Project Names

One last thing to look out for is the offset of the project names. When the size of the project square changes, some of the project names need to be offset further down or else they start to creep up and show before the user hovers over the project box. See the screen shot below for what I'm describing.

Screen Shot 2021-09-07 at 8 58 28 PM

I only noticed it at the smaller breakpoints, but as you make adjustments, that's something to keep in mind.

---

As always, let me know if you have any questions! You can comment here or reach me on Slack. I'll be able to respond within 24–48 hours to discussions and comments, but PR reviews will most likely be weekends only this month.

**Comment by arielj** [comment]
> # PR Feedback
> Hi @arielj! Thank you again for being patient while waiting for my response on this PR.
> 
> ## Layout Formatting
> I noticed that you used CSS grid to make the project boxes responsive. Is there a reason you chose grid over Bootstrap? That's the CSS framework we're currently implementing (I need to update it to v5.0 still).
> 
> Actually I'm just realizing now that some documentation wasn't brought over from the original repo we started this site on so you wouldn't have known that unless you're already familiar with Bootstrap's syntax. Ugh!
> 
> If you want to take a look at [Bootstrap Grid System's `.row-cols-*` class](https://getbootstrap.com/docs/4.6/layout/grid/#row-columns), you'll see how it works a lot like CSS grid. I'd prefer we use this to keep the same system throughout the codebase, plus it doesn't give off that shaky resizing effect as the user adjusts the window.
> 
> ## Breakpoints
> The number of columns you used at each breakpoint looks good to me! There was just one section that was a bit off. At `546px` it's a 2-column grid and at `547px` it jumps to a 3-column grid. Then at `578px` it reduces back down to a 2-column grid. Since it's such a short range, I'm assuming it's just a fluke. Could you look into that please?
> 
> ## Project Names
> One last thing to look out for is the offset of the project names. When the size of the project square changes, some of the project names need to be offset further down or else they start to creep up and show before the user hovers over the project box. See the screen shot below for what I'm describing.
> 
> Screen Shot 2021-09-07 at 8 58 28 PM
> 
> I only noticed it at the smaller breakpoints, but as you make adjustments, that's something to keep in mind.
> 
> As always, let me know if you have any questions! You can comment here or reach me on Slack. I'll be able to respond within 24–48 hours to discussions and comments, but PR reviews will most likely be weekends only this month.

hey sorry I should have asked about using css grid instead of bootstrap, I'm usually more familiar with css grid since it's more flexible but I understand it's better to keep consistency in the css, I'll refactor that to go back to bootstrap

I'll check the issue in that range where the grid changes the number of columns and the other :+1:

No problem on when there are comments or reviews, I also sometimes have to wait for the weekends to do this!

**Comment by arielj** [comment]
hey @meg-gutshall I created PR #28 that should fix the responsiveness for this same page but I created it from a different branch so I don't have these extra commits. This PR can be closed.

**Comment by meg-gutshall** [comment]
Closed in favor of PR #28

**Pull request closed without merging**
